PORT: 3000
PREFIX: api

# 正常token2小时
tokenExpire: 2
# 刷新过期时间为7天
refreshTokenExpire: 7

# 默认密码
defaultPassword: 123456

# 数据库配置
datasource:
  driverName: mysql
  host: localhost
  port: 3306
  database: nestjs-mysql-api
  username: root
  password: abcd1234
  charset: utf8mb4
  loc: Asia/Shanghai
  logging: true

# 腾讯地图api
lbsKey: LW7BZ-NB7C5--QNDSX-VCZVT-D7FQ4
